apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: robin
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: robin-password
    key: password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete  
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-robin
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: "*"
  table: "*"
  username: robin
  grantOption: true
  host: "%"