apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql-in
  namespace: default

spec:
  entryPoints:
    - mysql

  routes:
  - match: HostSNI(`db.wrenspace.dev`)
    services:
    - name: mariadb-port
      port: 3306