apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secret
  namespace: mariadb-sys
spec:
  encryptedData:
    password: AgCtoLcupHcBHiEISF9qDzva5xJwj6jk29Ae6NcpTfrLPJbEA4mhygYH5gQ3/055DJeTKN2g+A/8mxGeQ/jW4ETRY0SwwFrpQthDNEZ8hYNfvplIV2Kl51QD25FswhoyS/tffAXCfahVx8N3K7uZ5EPA+Fa1CuhPVI1LMmDzSm/kcpiW6lJNX25S29RazhGJjlafU8DqWN5N+T6D+iYWuQf38OPpT0ElVARw9iwOZmq+amtGAnvjWaDOfP/4+lQOy+Mwr6ZILncxRyRPtesHb8b6DA2yKyYxyI+tT3Xr7xtXLurn5Quz9UWJaCpeJKHT9PQpNvk6E2UwGRwKRycmz8WyMP9miSTkpdjQuyYoHlpsZbKFUgHhobbAWDp3ECu2b/+EdGE74xEV/4yuAsY4yyGUekW6xp2Gjkk5kj031kHSwEG3udZWI+xWtyCVQLyF+HzbZGHk60mFB4W5DUVw0lcbiV21LEzfrDTqCug1cWjVEX2a0aK4eH6EEj1LSKEf5y1Iq3hcYTWhZ+nQ3HSX1h/dicOsRoPb/PXmMvoBqTdxRpr7ZxNLKLKJujYgsrQaxRl7kLhCngzkMl9SDeJ70Pv8sAS0BlWaLyoNDsxuwapknR0PXHCZhSAzvfWe2ay3/dJVQ5nlIk+/UJ4mGPYq4VdNPrhP0B3tR1fkP1FqFjIW97c5P71TTtO4uhdO/Nz9UB+UgWYQxdGl0B/UAg==