apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb-sys
  labels:
    app.kubernetes.io/name: mariadb
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 33306
      protocol: TCP
  selector:
    app.kubernetes.io/name: mariadb