version: '3'
services:
  statping:
    image: adamboutcher/statping-ng:latest
    restart: always
    network_mode: host
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080

volumes:
  statping_data:
