apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate
  namespace: flux-system
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: infrastructure
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./apps/infrastructure/renovate/manifests
  prune: true
