version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    networks:
      - caddy
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "${data_path}/navidrome:/data"
      - "${data_path}/media/music:/music:ro"
    deploy:
      labels:
        # ingress
        caddy: music.${base_domain}
        caddy.reverse_proxy: "{{ upstreams 4533 }}"
        caddy.tls: internal
        # homepage
        homepage.group: ${media_group}
        homepage.name: Navidrome
        homepage.icon: navidrome
        homepage.href: https://music.${base_domain}
        homepage.description: Music server compatible with Subsonic clients.
      placement:
        constraints:
          - node.labels.gigabit==true

networks:
  caddy:
    external: true