apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: media-stack
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@192.168.200.52/coffeeknife/media-stack.git
  ref:
    branch: main
  secretRef:
    name: flux-system