apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBp18gxN/laB4CvT10i2v/ovbBsTw1D1ii9i//6MUI8HBwiCqAMqqo9rQrB3gXUcihYwg0ywRLRzLlW8Z0lmaeGpJnA1SRK4G0qGXNpsYfEjAS1UpnLQSgrbltTXHL1RIF2EY+VBJeyIzthYI+nTcsUTU/wTYv0mtxF2c1O3bisupLvPxJ2hIuEZjetyxEOJUY7bHNeCe0XrPmMZI1k4p4fz2kUCocvwU21bgHHXo0TAwGwap7f+DJJRqKmvbjtFKPeSqm5CSXWYs2b5VDChmkIreM7IcZhDG4qtHpPQ/2GBGMpg5GwNM7w9vCRf8XP73a2OOOi6l8A/xaONqRyd1Vxin0tLZJJxDuo8tmjjqLj9h/ycBn3S7pfY5c3UB3MLl1N7PRL/pRanLBk8shM7IEpe3JDuz6TPF0jULKym2yNhKmZmaFru/p/BT0yV5TKtkt6Dqd1zjjR4/K3QbBm4h9nXvuoTa5ZYjWeQvkPp6Tgl544TTxjFOKEKCrsx+YoLOz8bMTYBolurn6bRXGpxZkACfAI6186nz7rdRBWTA16B3WUTFM1xIUmP8xXeL4nCAZ7aZnUxCW5Dhu2mz14LoBzacbfnkCD8l4H09THnqbQHRD1U07ehyTzJ2ccNuQ3w+yL4qY5KslQV0csfsbMBUnEljeeQvQL+YBHixop16bII2pqdBu5nD8bNHokSLnNPBAkKnQl8TlDGyE1lFquj7dtwowyE+LzFJpJLCHXOxVmn+/B1lqt2sXApkU06w==
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: gitea-receiver
  namespace: flux-system
spec:
  type: generic
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: media-stack
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-webhook
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
spec:
  rules:
    - host: flux-webhook.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-receiver
                port:
                  number: 80
  tls:
    - hosts:
        - flux-webhook.wrenspace.dev
      secretName: flux-webhook-tls