version: '3'

networks:
  host:
    external: true
  caddy:
    external: true

services:
  netdata:
    image: netdata/netdata
    pid: host
    networks:
      - host
      - caddy
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${netdata_config}:/etc/netdata
      - ${netdata_lib}:/var/lib/netdata
      - ${netdata_cache}:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro
    deploy:
      labels:
        # ingress
        caddy: ${netdata_domain}
        caddy.reverse_proxy: "{{upstreams 19999}}"
        caddy.tls: internal
        # homepage
        homepage.group: ${netdata_group}
        homepage.name: Netdata
        homepage.icon: netdata
        homepage.href: https://${netdata_domain}
        homepage.description: Network monitor utility.
      placement:
        constraints:
          - node.role==manager