apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - "argocd.wrenspace.dev"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cert-issuer
  usages:
    - digital signature
    - key encipherment