apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cockpit
  namespace: external-ingress
spec:
  dnsNames:
    - nix.wrenspace.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cert-issuer
  secretName: cockpit-tls
  usages:
    - digital signature
    - key encipherment
---
apiVersion: v1
kind: Service
metadata:
  name: cockpit
  namespace: external-ingress
spec:
  ports:
  - name: app
    port: 9090
    protocol: TCP
    targetPort: 9090
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cockpit
  namespace: external-ingress
subsets:
- addresses:
  - ip: 192.168.1.69
  ports:
  - name: app
    port: 9090
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: cockpit-transport
  namespace: external-ingress
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cockpit
  namespace: external-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nix.wrenspace.dev`)
      services:
        - name: cockpit
          port: 9090
          serversTransport: cockpit-transport
          scheme: https
  tls:
    secretName: cockpit-tls
