apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crafty-controller
  namespace: external-ingress
spec:
  dnsNames:
    - craft.wrenspace.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cert-issuer
  secretName: crafty-controller-tls
  usages:
    - digital signature
    - key encipherment
---
apiVersion: v1
kind: Service
metadata:
  name: crafty-controller
  namespace: external-ingress
spec:
  ports:
  - name: app
    port: 8443
    protocol: TCP
    targetPort: 8443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: crafty-controller
  namespace: external-ingress
subsets:
- addresses:
  - ip: 192.168.1.74
  ports:
  - name: app
    port: 8443
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: crafty-controller-transport
  namespace: external-ingress
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crafty-controller
  namespace: external-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`craft.wrenspace.dev`)
      services:
        - name: crafty-controller
          port: 8443
          serversTransport: crafty-controller-transport
  tls:
    secretName: crafty-controller-tls
