apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin
  namespace: external-ingress
spec:
  dnsNames:
    - stream.wrenspace.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cert-issuer
  secretName: jellyfin
  usages:
    - digital signature
    - key encipherment
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: external-ingress
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8096
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin
  namespace: external-ingress
subsets:
- addresses:
  - ip: 192.168.1.210
  ports:
  - name: app
    port: 8096
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-headers
  namespace: external-ingress
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Host: "Host"
      X-Forwarded-Proto: "https"
      X-Forwarded-For: "RemoteAddr"
      Upgrade: "websocket"
      Connection: "Upgrade"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: external-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`stream.wrenspace.dev`)
      services:
        - name: jellyfin
          port: 80
      middlewares:
        - name: jellyfin-headers
  tls:
    secretName: jellyfin