apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
  namespace: paperless
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: paperless
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password