---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-pv
  namespace: paperless
spec:
  storageClassName: paperless-nfs
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/birdpool/filing
    server: 192.168.1.69
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc
  namespace: paperless
spec:
  storageClassName: paperless-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi