apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  namespace: paperless
  annotations:
    configmap.reloader.stakater.com/reload: "paperless-config"
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
        app.kubernetes.io/name: paperless
    spec:
      volumes:
        - name: paperless-pvc
          persistentVolumeClaim:
            claimName: paperless-pvc
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-consume
          persistentVolumeClaim:
            claimName: paperless-consume
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:2.18
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
          - name: http
            containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: paperless-pvc
            mountPath: /usr/src/paperless/media
          - name: paperless-data
            mountPath: /usr/src/paperless/data
          - name: paperless-consume
            mountPath: /usr/src/paperless/consume
        envFrom:
          - configMapRef:
              name: paperless-config
        env:
          - name: AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: client-secret
          - name: PAPERLESS_SOCIALACCOUNT_PROVIDERS
            value: |
              {
                "openid_connect": {
                  "SCOPE": ["openid", "profile", "email"],
                  "OAUTH_PKCE_ENABLED": true,
                  "APPS" : [
                    {
                      "provider_id": "authelia",
                      "name": "Authelia",
                      "client_id": "paperless",
                      "secret": "$(AUTH_SECRET)",
                      "settings": {
                        "server_url": "https://auth.wrenspace.dev",
                        "token_auth_method": "client_secret_basic"
                      }
                    }
                  ]
                }
              }
          - name: PAPERLESS_DBPASS
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: password
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-creds
                key: password
          - name: PAPERLESS_REDIS
            value: "redis://default:$(REDIS_PASS)@redis-master.paperless.svc.cluster.local:6379"
