apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  namespace: paperless
spec:
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      volumes:
        - name: paperless-pvc
          persistentVolumeClaim:
            claimName: paperless-pvc
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:2.18
        resources:
          requests:
            cpu: 250m
            memory: 1024Mi
          limits:
            cpu: 500m
            memory: 2048Mi
        ports:
          - name: http
            containerPort: 8000
        volumeMounts:
          - name: paperless-pvc
            mountPath: /usr/src/paperless/media
        envFrom:
          - configMapRef:
              name: paperless-config
        env:
          - name: PAPERLESS_DBPASS
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: password
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-creds
                key: password
          - name: PAPERLESS_REDIS
            value: "redis://default:$(REDIS_PASS)@redis-master.paperless.svc.cluster.local:6379"
