apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  sources:
    - path: ''
      repoURL: https://traefik.github.io/charts
      targetRevision: 37.0.0
      chart: traefik
      helm:
        valueFiles:
          - $values/kubernetes/traefik/values-nextcloud.yaml
    - repoURL: https://git.wrenspace.dev/coffeeknife/homelab
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true