# nfs config
---
- name: Mount nfs share at boot
  hosts: "{{ book_hosts | default('all') }}"
  collections:
    - ansible.posix
  tasks:
    - name: Install nfs utils
      package:
        name: nfs-common
        state: present
    - name: Mount specified nfs share
      mount:
        src: "{{ nfs_ip }}:{{ share_path }}"
        path: "{{ share_path }}"
        fstype: nfs
        state: mounted
