# TODO: make ansible playbook for one-click deployment of the whole swarm
---
- name: Initialize docker swarm
  hosts: "{{ hosts | default('workers') }}"
  collections:
    - community.docker
  tasks:
    - name: Join docker swarm
      docker_swarm:
        state: join
        join_token: "{{ join_token }}"
        remote_addrs: ["{{ controller_ip }}:2377"]
