version: '3'
services:
    scanservjs:
        networks:
          - caddy

        volumes:
            - /var/run/dbus:/var/run/dbus
        restart: unless-stopped
        privileged: true
        image: sbs20/scanservjs:latest
        deploy:
          labels:
            # ingress
            caddy: scan.${base_domain}
            caddy.reverse_proxy: "{{ upstreams 8080 }}"
            caddy.tls: internal
            # homepage
            homepage.group: ${svc_group}
            homepage.name: ScanServJS
            homepage.icon: scanservjs
            homepage.href: https://scan.${base_domain}
            homepage.description: Web UI for home scanners

networks:
  caddy:
    external: true