version: '3.3'
services:
    metatube:
        container_name: metatube
        restart: always
        image: jvt038/metatube:latest
        networks:
          - caddy
        environment:
            - PORT=5050
            - HOST=0.0.0.0
        volumes:
            - '${metatube_downloads}:/downloads:rw'
            - '${metatube_db}:/database:rw'
            - '${metatube_migrations}:/config/migrations:rw'   
        deploy:
          labels:
            # ingress
            caddy: ${metatube_domain}
            caddy.reverse_proxy: "{{ upstreams 5050 }}"
            caddy.tls: internal
            # homepage
            homepage.group: ${metatube_group}
            homepage.name: Metatube
            homepage.icon: youtubedl
            homepage.href: https://${metatube_domain}
            homepage.description: YouTube archiver with automatic metadata tagging.
          placement:
            constraints:
              - node.labels.gigabit==true

networks:
  caddy:
    external: true