version: '3.3'
services:
    metatube:
        container_name: metatube
        restart: always
        image: jvt038/metatube:latest
        networks:
          - caddy
        environment:
            - PORT=5050
            - HOST=0.0.0.0
        volumes:
            - '${storage_path}/metatube/downloads:/downloads:rw'
            - '${storage_path}/metatube/database:/database:rw'
            - '${storage_path}/metatube/migrations:/config/migrations:rw'   
        deploy:
          labels:
            # ingress
            caddy: yt-dl.${base_domain}
            caddy.reverse_proxy: "{{ upstreams 5050 }}"
            caddy.tls: internal
            # homepage
            homepage.group: ${dl_group)
            homepage.name: Metatube
            homepage.icon: youtubedl
            homepage.href: https://yt-dl.${base_domain}
            homepage.description: YouTube archiver with automatic metadata tagging.
          placement:
            constraints:
              - node.labels.gigabit==true

networks:
  caddy:
    external: true