apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: firefox-sync
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
---
apiVersion: v1
kind: Secret
metadata:
  name: firefox-sync-secret
  namespace: firefox-sync
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret
