version: '3'
services:
  otterwiki:
    image: redimp/otterwiki
    volumes:
      - ${data_path}/otterwiki:/app-data
    networks:
      - caddy
    deploy:
      labels:
        # ingress
        caddy: wiki.${base_domain}
        caddy.reverse_proxy: "{{ upstreams 80 }}"
        caddy.tls: internal
        # homepage
        homepage.group: ${svc_group}
        homepage.name: OtterWiki
        homepage.icon: google-docs
        homepage.href: https://wiki.${base_domain}
        homepage.description: Local wiki

networks:
  caddy:
    external: true