version: "3"
services:
  vaultwarden:
    networks:
      - caddy
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - 'ADMIN_TOKEN=${vaultwarden_admin}'
    ports:
      - 8445:80
    volumes:
      - ${data_path}/vaultwarden:/data:rw
    deploy:
      labels:
        # ingress
        caddy: pass.${base_domain}
        caddy.tls: internal
        caddy.reverse_proxy: "{{ upstreams 80 }}"
        # homepage
        homepage.group: ${svc_group}
        homepage.name: Vaultwarden
        homepage.icon: vaultwarden
        homepage.href: https://pass.${base_domain}
        homepage.description: Password manager that works with Bitwarden clients. 
      placement:
        constraints:
          - node.labels.gigabit==true

networks:
  caddy:
    external: true