apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  passwordSecretKeyRef:
    name: mariadb-secret
    key: password
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: nextcloud-perm
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  privileges:
    - "ALL"
  database: "nextcloud-db"
  table: "*"
  username: nextcloud