apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: MYSQL_PASSWORD
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-secret
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_ADMIN_USER: AgBuu+PJyq9XPSW3a3eQZDyu/BvE9rfM4oLzjV5WECHVZvOK4S4jjATfcgHveCd/LoHuOcjz57OGeNFfASmflnTzdoZcDMv99SGEr0D6ZL8mIhSo9hu94XEuWfgJPzbFPkq715an8GegzBA7UWTyD330DYf2soE1eEfzCAuptjzZ1PC2torrYgWczY9iRIUJ2BVqeo9E/74DTV+nk6RTbqUI7HLdHqsS73XVSx2RCkqh8v9fqXLOc7x1ZWPKV/vie6HfzmheEUxmGNEdlsuaNB+/jS9PqEsuXTiYWlAQ2XhN6y/uTS2B/j9rc8PqA5JVHQckE6WpcNsX/KPi7gowVgIwQXuNbhBDoX/cd7zoOYLV9V5Qm1IJhKpNlDDxFRcndpWtsEowoBTYa2xSkCB+XIseZDh0N4soggwMmjhYsCcaFmq+Gbmf29mVRy2MClMnOH+nQcNqyat0N3oq7ID3U+8r7PB5sQtIa9d1xj0iPSU7sqoLxQwH9oqOHwVbyZQeydxm2FSZXeZD033WYmJ3ytA57F/L38aeTG50OyigLxaGV4cBCWi8lSZ+2b+fkTG4T7ynU4siCVlesvKZEVOdfxPmX6+hmLihvT3Tb7n7AziXfPEzGXNq4MaoeNGJC1tJXgIsF77NOwqJrXF8a3Zc7xUysNAwxxzHWgKXDuIRNuyYrTieaRwkmuPYgyMGgjrh0NSK6Hz2vw==
    NEXTCLOUD_ADMIN_PASSWORD: AgCezYzMtxjdReKxgwVjzX1LRfVde+YkI0bLCEaLHU+fXJJFuf3zuWkvgb3lH5Hpi4ElfIaZBoe4LIHWm0PqLJdA/KawKJVmy4wQR1ecfB7ef+QLKOFtTg0oD1pecp4MM9EUamOkYPxjWkPuXb5IjMJ46mix/xLYJnHLS4uML6saQZdpyhqZZSp99gjSIi2DBOWoR/gRpGGPcX7o6Aa+PhkcSHoK2SLudo43zlUM7B9BYObAKPXo/bYZuaGt2z0SUoDjz+Ji/TF8r3xggdlyGsTG+qRpWFNhShQdGSrRxh6KmRAfTuDqI/fZbCV3BIMh3SAnux6lRSTQWQWK27oncp0h9a94z4+PHea555Gf3QavQUXuQWq00ePDS4uf5oeF+1CDVejxhb/LVmTuYam6VK4Qy+ra/EE6WYe3oXDkrH2U3NmHdxdsx7/6LRLu7h1mycNBIjzLy49d9qxb/6KakgT3yerOfUyheKXYLt4FTqbPuqd1eiTTxFuNIqu1I8Ojfa4IGXWXxGGOGQJDFEjmU9H4dZui3tgyWJ/Gd0HFhJyaObiIxzvWdbvWUtW2/HQrJxMEPqjoPpILheXNxeKDDTL3QUm8JGX15ZMkyOuB2Jl/Rp5SLjG7SSRoPPggBw5rYQeuoUaPxz5tCSB1G9MGbvPai1zHcedUycp1f1hW8thozGoHXSt61ri/txH2Z2tMxvH0SuateOxz0LtfLQ==
