apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nextcloud
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloudmiddleware
  namespace: nextcloud
spec:
  redirectRegex:
    regex: "^https?://drive\\.wrenspace\\.dev/(?:\\.well-known/carddav|\\.well-known/caldav)$"
    replacement: "https://drive.wrenspace.dev/remote.php/dav"
    permanent: true
  headers:
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Xss-Protection: "1; mode=block"
      X-Robots-Tag: "noindex, nofollow"
      X-Frame-Options: "SAMEORIGIN"
      Referrer-Policy: "no-referrer"
      Strict-Transport-Security: "max-age=15552000"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: nextcloudmiddleware@kubernetescrd
    cert-manager.io/cluster-issuer: cert-issuer
spec:
  rules:
    - host: drive.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
  tls:
    - hosts:
        - drive.wrenspace.dev
      secretName: nextcloud-tls