nextcloud:
  host: drive.wrenspace.dev
  existingSecret:
    enabled: true
    secretName: admin-secret
    usernameKey: username
    passwordKey: password
  defaultConfigs:
    imaginary.config.php: true
  configs:
    domains.config.php: |-
      <?php
        $CONFIG = array(
          'trusted_domains' =>
            array(
              0 => 'drive.wrenspace.dev'
            ),
          'trusted_proxies' =>
            array (
              0 => '192.168.0.0/24'
            )
        );
    maintenance.config.php: |-
      <?php
        $CONFIG = array(
          'maintenance_window_start' => 6,
        );

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  existingSecret:
    enabled: true
    secretName: mariadb-secret
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: database

redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: password

imaginary:
  enabled: true

collabora:
  enabled: true
  collabora:
    aliasgroups:
      - host: "https://drive.wrenspace.dev:443"
    extra_params: --o:ssl.enable=false --o:ssl.termination=true
    server_name: docs.wrenspace.dev
  ingress:
    className: "traefik"
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: docs.wrenspace.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - docs.wrenspace.dev
        secretName: nextcloud-tls

cronjob:
  enabled: true

ingress:
  className: traefik
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: drive.wrenspace.com
      paths:
        - /
  tls:
    - hosts:
        - drive.wrenspace.dev
      secretName: nextcloud-tls

service:
  type: ClusterIP
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"

persistence:
  enabled: true
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-pvc