nextcloud:
  host: drive.wrenspace.dev
  existingSecret:
    enabled: true
    secretName: admin-secret
    usernameKey: username
    passwordKey: password
  extraEnv:
    - name: TRUSTED_PROXIES
      value: "10.0.0.0/8"
  extraVolumes:
    - name: oauth-secret
      secret:
        secretName: oauth-secret
        items:
          - key: client-secret
            path: oidc.secret.config.php
  extraVolumeMounts:
    - name: oauth-secret
      mountPath: /var/www/html/config/oidc.secret.config.php
      subPath: oidc.secret.config.php
  configs:
    maintenance.config.php: |-
      <?php 
      $CONFIG = array(
        'maintenance_window_start' => 7,
      );
    phone-region.config.php: |-
      <?php
      $CONFIG = array(
        'default_phone_region' => 'US',
      );
    oidc.config.php: |-
      <?php
      $CONFIG = array(
        'allow_user_to_change_display_name' => false,
        'oidc_login_provider_url' => 'https://auth.wrenspace.dev',
        'oidc_login_client_id' => 'nextcloud',
        'oidc_login_auto_redirect' => false,
        'oidc_login_code_challenge_method' => 'S256',
        'oidc_login_end_session_redirect' => false,
        'oidc_login_button_text' => 'Log in with Authelia',
        'oidc_login_hide_password_form' => true,
        'oidc_login_proxy_ldap' => true,
        'oidc_login_scope' => 'openid profile',
        'oidc_login_attributes' => array (
            'id' => 'preferred_username',
            'name' => 'name',
            'mail' => 'email',
            'groups' => 'groups',
            'ldap_uid' => 'preferred_username',
        ),
      );

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  existingSecret:
    enabled: true
    secretName: mariadb-secret
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: database

redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: password

imaginary:
  enabled: true

collabora:
  enabled: true
  collabora:
    aliasgroups:
      - host: "https://drive.wrenspace.dev:443"
    extra_params: --o:ssl.enable=false --o:ssl.termination=true
    server_name: docs.wrenspace.dev
  ingress:
    className: "traefik"
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: docs.wrenspace.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - docs.wrenspace.dev
        secretName: nextcloud-tls-collabora

cronjob:
  enabled: true

ingress:
  className: traefik
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-hsts@kubernetescrd
  hosts:
    - host: drive.wrenspace.dev
      paths:
        - /
  tls:
    - hosts:
        - drive.wrenspace.dev
      secretName: nextcloud-tls

service:
  type: ClusterIP
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"

persistence:
  enabled: true
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-pvc

resources:
  requests:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"

# prevent probes from interrupting startup
livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false