nextcloud:
  host: drive.wrenspace.dev
  existingSecret:
    enabled: true
    secretName: admin-secret
    usernameKey: username
    passwordKey: password
  extraEnv:
    - name: TRUSTED_PROXIES
      value: "10.0.0.0/8"
  configs:
    maintenance.config.php: |-
      <?php 
      $CONFIG = array(
        'maintenance_window_start' => 7,
      );

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  existingSecret:
    enabled: true
    secretName: mariadb-secret
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: database

redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: password

imaginary:
  enabled: true

collabora:
  enabled: true
  collabora:
    aliasgroups:
      - host: "https://drive.wrenspace.dev:443"
    extra_params: --o:ssl.enable=false --o:ssl.termination=true
    server_name: docs.wrenspace.dev
  ingress:
    className: "traefik"
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: docs.wrenspace.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - docs.wrenspace.dev
        secretName: nextcloud-tls

cronjob:
  enabled: true

ingress:
  className: traefik
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: drive.wrenspace.dev
      paths:
        - /
  tls:
    - hosts:
        - drive.wrenspace.dev
      secretName: nextcloud-tls

service:
  type: ClusterIP
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"

persistence:
  enabled: true
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-pvc

resources:
  requests:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"

# prevent probes from interrupting startup
livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false