apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: lldap
spec:
  dnsNames:
    - id.wrenspace.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cert-issuer
  secretName: cert
  usages:
    - digital signature
    - key encipherment