apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-tls
  namespace: lldap
spec:
  secretName: lldap-tls-secret
  issuerRef: 
    group: cert-manager.io
    kind: ClusterIssuer
    name: cert-issuer
  dnsNames:
    - id.wrenspace.dev