apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-config
  namespace: lldap
data:
  LLDAP_LDAPS_OPTIONS__ENABLED: 'true'
  LLDAP_LDAPS_OPTIONS__CERT_FILE: '/cert/tls.cert'
  LLDAP_LDAPS_OPTIONS__KEY_FILE: '/cert/tls.key'