apiVersion: v1
kind: Secret
metadata:
  name: lldap-db-secret
  namespace: postgres-db
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "password"
    secret-generator.v1.mittwald.de/regenerate: "true"
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
