apiVersion: v1
kind: Secret
metadata:
  name: lldap-db-secret
  namespace: postgres-db
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "password"
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
---
apiVersion: postgresql.cnpg.io/v1
kind: Role
metadata:
  name: lldap
  namespace: postgres-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: postgres-db
  password:
    valueFrom:
      secretKeyRef:
        name: lldap-db-secret
        key: password
  login: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lldap-db
  namespace: postgres-db
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: lldap-db
  owner: lldap
  cluster:
    name: postgres-db
  extensions:
  - name: bloom
    ensure: present