apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: lldap
  namespace: lldap
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: lldap
  namespace: lldap
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: mariadb-pass
    key: password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete  
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-lldap
  namespace: lldap
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: "lldap"
  table: "*"
  username: lldap
  grantOption: true
  host: "%"