apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lldap-db
  namespace: postgres-db
spec:
  name: lldap-db
  owner: lldap
  cluster:
    name: postgres-db
  extensions:
  - name: bloom
    ensure: present