apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lldap
    spec:
      containers:
        - name: lldap
          image: lldap/lldap:stable
          ports:
          - name: ldap
            containerPort: 3890
          - name: http
            containerPort: 17170
          - name: ldaps
            containerPort: 6360
          envFrom:
            - configMapRef:
                name: lldap-config
            - secretRef:
                name: lldap-secret
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: LLDAP_DATABASE_URL
              value: "mysql://lldap:$(DB_PASSWORD)@mariadb.mariadb-sys.svc.cluster.local:3306/lldap-db"
          volumeMounts:
          - name: data
            mountPath: /data
          - name: cert
            mountPath: /cert
          resources:
            requests:
              memory: 128Mi
              cpu: 300m
            limits:
              memory: 256Mi
              cpu: 500m
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lldap-key-pvc
      - name: cert
        secret:
          secretName: cert
          items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt