apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap

spec:
  selector:
    app: lldap
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
  - name: ldaps
    protocol: TCP
    port: 6360
    targetPort: ldaps
  - name: ldap
    protocol: TCP
    port: 3890
    targetPort: ldap
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: lldap
  namespace: lldap
spec:
  rules:
  - host: id.wrenspace.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lldap
            port:
              name: http
  tls:
    - secretName: lldap-tls-secret