apiVersion: v1
kind: Service
metadata:
  name: lldap-internal
  namespace: lldap
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lldap
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: ldap
    port: 3890
    targetPort: ldap
  - name: ldaps
    port: 6360
    targetPort: ldaps
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lldap
  namespace: lldap
spec:
  tls:
    secretName: cert
  entryPoints:
    - websecure
  routes:
    - match: Host(`id.wrenspace.dev`)
      kind: Rule
      services:
        - name: lldap-internal
          port: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: lldap-ldaps
  namespace: lldap
spec:
  entryPoints:
    - ldaps
  routes:
    - match: HostSNI(`id.wrenspace.dev`)
      services:
        - name: lldap-internal
          port: ldaps