---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: runner-token
  namespace: gitea-actions
spec:
  encryptedData:
    runner-token: AgBiUywCfmqUgpmBHTswvCOjfyLc0MJn4Ie/JtrwCZixq6GUPx+huUTZB3VSAa2yypcajl0Xt048UV+qSYP8Y5TTa64vptsCsov2Jbnfsc2tEfhH+3vvjYhjPuY2pFdEgxeCyeQMmST5LtmKiF+J+qFYfB4rkHOdMe/D2hYOowtKMHUoqVW4thWK5wxu4x50g9ue3E7ge4111+4FrU2qs6r8MBcfIGpvLQtub9acmDEGr7MDJNdIdjyo1i2AhhASMwnHnr2UHIb2A5Qyk2J/EophRC4zlhPj6KURko16KHn0UAjzbCjFaIrb7zy5mI77VDqwKFA4MhZ8Rl0l2X1NqJz6TXU267FzE71gdxaujvMV7rixCKRQTe3gb6G28I/jWxU7+lqUxHUri6ZrH8GHWS5f+EVsCAB3+yIKv1wMGqJmi5tQGbpAvZAGUHD/Oj2xp4hEJQWZXVc51SMVGMsQzMp7ZbaU4NMA0LAJz+zwgUsS25+Ps3Q7x++bOqto3qq9rcBX9CmE9q4JYyIS8d1I13q2Lh2IGnkiIMY4mKVE6djwcadlyBNdnsmiEb3GvSixnAlHb4aftFKfAHWPpNdIcYje3unQvlw0LULsDummYnNpeUFmI988jiXvSgVTZJvVXxS+/94lJnzfSVdiZY4HpW/N15uSoKvgk7k75ouUKkbfcbfNL9pGcWwgjANo0SjEUrvD1791d8v+z+fCI2yUwpv1sLsRSwTtH9+FjX5rzOybviY1UP7faBgS
  template:
    metadata:
      name: runner-token
      namespace: gitea-actions
      labels:
        app.kubernetes.io/name: gitea-actions
        app.kubernetes.io/part-of: infrastructure
