apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-secrets
  namespace: authelia
spec:
  encryptedData:
    nextcloud.secret.txt: AgBKgMuZlrEM8QCkt/OQJZEWVqxc+EoYoca7UPJMSxciAnsWjfqvgMm0bGh/TL1wcmKFAdK3HwmVbeJZtk8pmOn0G/+btKSjZIQJoBlZiiI50SqzKsWy1Qb0Tx6V6hOZmtQVTmznzN1E1d7ytHCyQfcvFrMyMh5NJdb1mqhCyekL02qAB6Aang0R9oGfRL40v2Gyixa2a7uf8bge0CNDH1fvGlQPFNzpw7J2+pPhtGXWz2vm0B7BSLn3BwgiPF5aQR4HBHvwT7k4nvjoocsW9fxUNT4IIr0irgskeFQbLxhbysZHx+LFc8oZ+9S6HFXgzpzWcexPtq8I63B8PRS2QRP5oITAeqYJgv8Qw1K9GSoJkMDDXurYCoaI26MMcdMEIYrxfbcOBI45ZBJhDwMOZFrSQk2JkMqGz3+ohjCJ71ZYqzhaa1bljrDrxe+y/1bEyh0tjcBuWfy8DpS4wr+YJDFm64kJ8DCXe+RA0Ma6Qyl0K0Vjal+UWSpY1xQKcth1NcMSHhl7zHi7DTXaZZauoZovWWMzlNYVAOKpf8EFtGXssZzOp98mXtCmRDXbzhxAoZgqjrbJar1V5VM9s3Zq7L82831ueW96r88L2Ln7CcOQuk3GyOZ696xoMouicMpacCqix8dYxlYLeORnYNSr5k3j0T9tCZhu05FyhDr9Xi732heJsm8S4jl6bdC1bvOUQcu6jk+matmtoBUjj6jot5hpgnxUFClcpbuwQIhx3NOV4SofN+/EMvmUB1Ng9nqWTyYMJkIXHDEMmIYim8ite/H4O/cNPa6jLSRQln5OQUj2qSUTbEPdpIXdu01GnbCyLNx1
    