configMap:
  session:
    cookies: [ { domain: wrenspace.dev } ]
  storage:
    local: { enabled: true } # temporary
  notifier:
    filesystem: { enabled: true } # temporary
  authentication_backend:
    ldap:
      enabled: true
      implementation: lldap
      address: ldaps://lldap.lldap.svc.cluster.local:6360
      tls:
        server_name: id.wrenspace.dev
      base_dn: dc=wrenspace,dc=dev
      user: uid=search,ou=people,dc=wrenspace,dc=dev
      password: { secret_name: lldap-auth }

secret:
  existingSecret: crypto
  additionalSecrets:
    lldap-auth:
      items: [ { key: password, path: authentication.ldap.password.txt } ]

# temp
pod:
  kind: Deployment