configMap:
  session:
    cookies:
      domain: wrenspace.dev
  storage:
    local:
      enabled: true
  notifier:
    filesystem:
      enabled: true
  authentication_backend:
    file:
      enabled: true