configMap:
  session:
    cookies: 
      - domain: wrenspace.dev
  storage:
    local:
      enabled: true
  notifier:
    filesystem:
      enabled: true
  authentication_backend:
    ldap:
      enabled: true
      implementation: lldap
      address: ldaps://lldap-internal.lldap.svc.cluster.local:6360
      base_dn: DC=nest,DC=internal
      user: UID=search,OU=people,DC=nest,DC=internal
      password: { secret_name: lldap-auth }
      tls:
        server_name: 'id.wrenspace.dev'
  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key_id: default
          algorithm: RS256
          use: sig
          key: { path: /secrets/jwk-rsa/private.pem }
      cors:
        endpoints: [ userinfo, authorization, token, revocation, introspection ]
        allowed_origins_from_client_redirect_uris: true
      claims_policies:
        legacy:
          id_token: [ email, email_verified, alt_emails, name, preferred_username, groups ]

      clients: 
        - client_id: gitea
          client_name: Gitea
          client_secret: { path: /secrets/client-secrets/gitea.secret.txt }
          public: false
          authorization_policy: 'one_factor'
          require_pkce: false
          redirect_uris:
            - 'https://git.wrenspace.dev/user/oauth2/authelia/callback'
          scopes:
            - 'openid'
            - 'email'
            - 'profile'
          response_types:
            - 'code'
          grant_types:
            - 'authorization_code'
          access_token_signed_response_alg: 'none'
          userinfo_signed_response_alg: 'none'
          token_endpoint_auth_method: 'client_secret_basic'

service:
  type: LoadBalancer
secret:
  existingSecret: crypto
  additionalSecrets:
    jwk-rsa:
      items: [ { key: private.pem, path: private.pem } ]
    lldap-auth:
      items: [ { key: password, path: authentication.ldap.password.txt } ]
    client-secrets:
      items:
        - key: gitea
          path: gitea.secret.txt
ingress:
  enabled: false