configMap:
  session:
    cookies: [ { domain: wrenspace.dev, subdomain: auth } ]

  storage:
    mysql:
      enabled: true
      deploy: false
      address: tcp://mariadb-port.mariadb-sys.svc.cluster.local:3306
      database: authelia
      password:
        secret_name: db-auth

  notifier:
    smtp:
      enabled: true
      address: smtp://send.smtp-relay.svc.cluster.local
      sender: "Accounts <admin@wrenspace.dev>"
      disable_html_emails: true
      password: # temporary for testing
        disabled: true
      disable_require_tls: true

  authentication_backend:
    ldap:
      enabled: true
      implementation: lldap
      address: ldaps://lldap.lldap.svc.cluster.local:6360
      tls:
        server_name: id.wrenspace.dev
      base_dn: dc=wrenspace,dc=dev
      user: uid=search,ou=people,dc=wrenspace,dc=dev
      password: { secret_name: lldap-auth }

secret:
  existingSecret: crypto
  additionalSecrets:
    lldap-auth:
      items: [ { key: password, path: authentication.ldap.password.txt } ]
    db-auth:
      items: [ { key: password, path: storage.mysql.password.txt } ]

# temp
pod:
  kind: Deployment

ingress:
  enabled: true
  className: traefik
  certManager: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: cert-issuer
  tls:
    enabled: true
    secret: authelia-tls-cert