configMap:
  session:
    name: authelia_session
    same_site: lax
    cookies: 
      - domain: wrenspace.dev
        authelia_url: https://auth.wrenspace.dev
  storage:
    local:
      enabled: true
  notifier:
    filesystem:
      enabled: true
  access_control:
    default_policy: 'one_factor'
  authentication_backend:
    ldap:
      enabled: true
      implementation: lldap
      address: ldaps://lldap-internal.lldap.svc.cluster.local:6360
      timeout: 5s
      base_dn: DC=wrenspace,DC=dev
      user: UID=search,OU=people,DC=wrenspace,DC=dev
      password: { secret_name: lldap-auth }
      tls:
        server_name: 'id.wrenspace.dev'
  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key_id: default
          algorithm: RS256
          use: sig
          key: { path: /secrets/jwk-rsa/private.pem }
      cors:
        endpoints: [ userinfo, authorization, token, revocation, introspection ]
        allowed_origins_from_client_redirect_uris: true
      claims_policies:
        legacy:
          id_token: [ email, email_verified, alt_emails, name, preferred_username, groups ]

      clients: 
        - client_id: gitea
          client_name: Gitea
          client_secret: { path: /secrets/client-secrets/gitea.secret.txt }
          public: false
          authorization_policy: 'one_factor'
          require_pkce: false
          redirect_uris:
            - 'https://git.wrenspace.dev/user/oauth2/authelia/callback'
          scopes:
            - 'openid'
            - 'email'
            - 'profile'
          response_types:
            - 'code'
          grant_types:
            - 'authorization_code'
          access_token_signed_response_alg: 'none'
          userinfo_signed_response_alg: 'none'
          token_endpoint_auth_method: 'client_secret_basic'
        
        - client_id: 'paperless'
          client_name: Paperless-ngx
          client_secret: { path: /secrets/client-secrets/paperless.secret.txt }
          require_pkce: false
          authorization_policy: 'one_factor'
          consent_mode: 'implicit'
          redirect_uris:
            - 'https://file.wrenspace.dev/accounts/oidc/authelia/login/callback/'
          scopes:
            - 'openid'
            - 'email'
            - 'profile'
            - 'picture'
          userinfo_signed_response_alg: 'none'
          token_endpoint_auth_method: 'client_secret_basic'
          claims_policies:
            openid:
              preferred_username: "uid"
        
        - client_id: 'komga'
          client_secret: { path: /secrets/client-secrets/komga.secret.txt }
          require_pkce: false
          authorization_policy: 'one_factor'
          redirect_uris:
            - 'https://manga.wrenspace.dev/login/oauth2/code/authelia'
          scopes:
            - 'openid'
            - 'profile'
            - 'email'
          response_types:
            - 'code'
          grant_types:
            - 'authorization_code'
          access_token_signed_response_alg: 'none'
          userinfo_signed_response_alg: 'none'
          token_endpoint_auth_method: 'client_secret_basic'

        - client_id: 'jellyfin'
          client_secret: { path: /secrets/client-secrets/jellyfin.secret.txt }
          redirect_uris:
            - 'https://stream.wrenspace.dev/sso/OID/redirect/authelia'
          authorization_policy: 'one_factor'
          public: false
          require_pkce: false
          scopes:
            - 'openid'
            - 'profile'
            - 'email'
            - 'groups'
          response_types:
            - 'code'
          grant_types:
            - 'authorization_code'
          access_token_signed_response_alg: 'RS256'
          authorization_signed_response_alg: 'RS256'
          userinfo_signed_response_alg: 'RS256'
          token_endpoint_auth_method: 'client_secret_post'

        - client_id: linkwarden
          client_name: Linkwarden
          client_secret: { path: /secrets/client-secrets/linkwarden.secret.txt }
          public: false
          authorization_policy: one_factor
          consent_mode: implicit
          scopes:
            - openid
            - groups
            - email
            - profile
          redirect_uris:
            - https://links.wrenspace.dev/api/v1/auth/callback/authelia
          userinfo_signed_response_alg: none

service:
  type: LoadBalancer
secret:
  existingSecret: crypto
  additionalSecrets:
    jwk-rsa:
      items: [ { key: private.pem, path: private.pem } ]
    lldap-auth:
      items: [ { key: password, path: authentication.ldap.password.txt } ]
    client-secrets:
      items:
        - key: gitea
          path: gitea.secret.txt
        - key: paperless
          path: paperless.secret.txt
        - key: komga
          path: komga.secret.txt
        - key: jellyfin
          path: jellyfin.secret.txt
        - key: linkwarden
          path: linkwarden.secret.txt
ingress:
  enabled: false