configMap:
  session:
    cookies: 
      - domain: wrenspace.dev
  storage:
    local:
      enabled: true
  notifier:
    filesystem:
      enabled: true
  authentication_backend:
    ldap:
      enabled: true
      implementation: lldap
      address: ldaps://_ldaps.lldap-internal.lldap.cluster.local
      base_dn: DC=wrenspace,DC=dev
      user: UID=search,OU=people,DC=wrenspace,DC=dev
      password: { secret_name: lldap-auth }
service:
  type: LoadBalancer
secret:
  existingSecret: crypto
  additionalSecrets:
    lldap-auth:
      items: [ { key: password, path: authentication.ldap.password.txt } ]