configMap:
  session:
    cookies: 
      - domain: wrenspace.dev
  storage:
    local:
      enabled: true
  notifier:
    filesystem:
      enabled: true
  authentication_backend:
    ldap:
      enabled: true
      implementation: lldap
      address: ldaps://lldap-internal.lldap.svc.cluster.local:6360
      base_dn: DC=wrenspace,DC=dev
      user: UID=search,OU=people,DC=wrenspace,DC=dev
      password: { secret_name: lldap-auth }
      tls:
        server_name: 'id.wrenspace.dev'
service:
  type: LoadBalancer
secret:
  existingSecret: crypto
  additionalSecrets:
    lldap-auth:
      items: [ { key: password, path: authentication.ldap.password.txt } ]
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  traefikCRD:
    enabled: true
    routes:
      - rule: Host(`auth.wrenspace.dev`)
        services:
          - name: authelia
            port: 9091
    tls:
      secretName: authelia-tls-secret