apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: djjudas21
  namespace: flux-system
spec:
  interval: 24h
  url: https://djjudas21.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spoolman
  namespace: spoolman
  labels:
    app.kubernetes.io/name: spoolman
    app.kubernetes.io/part-of: 3d
spec:
  interval: 30m
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cert-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Spoolman
        gethomepage.dev/description: 3d printing spool manager
        gethomepage.dev/group: Services
      tls:
        - hosts:
            - spools.3d.wrenspace.dev
          secretName: spoolman-tls
      hosts:
        - host: spools.3d.wrenspace.dev
          paths:
            - path: /
      
  chart:
    spec:
      chart: spoolman
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: djjudas21
        namespace: flux-system