apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spoolmansync
  namespace: spoolman
  labels:
    app.kubernetes.io/name: spoolmansync
    app.kubernetes.io/part-of: 3d
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "SpoolmanSync"
    gethomepage.dev/group: "Services"
    gethomepage.dev/description: "Bambu Lab filament sync"
spec:
  rules:
    - host: sync.3d.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spoolmansync
                port:
                  name: http
  tls:
    - hosts:
        - sync.3d.wrenspace.dev
      secretName: spoolmansync-tls
