apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoolmansync-data
  namespace: spoolman
  labels:
    app.kubernetes.io/name: spoolmansync
    app.kubernetes.io/part-of: 3d
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
