apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lubelogger
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./apps/services/lubelogger/manifests
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: lubelogger-oidc-secret
