apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgCVIRterFKjGcp15yHpZrv1u7PISYIodQHtNGMRnmCRlDer2n6JIuH9GP5+391EY/U0mQgAfZ7RW2PpZU760h2bWa8JzUbkibFHrSOPkgF7HdjR529AbhcYqG3BAG6++VYSHSlaB9eeLTm9htJKbZfIioJtGx2pXfL7wfHytPqwkQYnL3S8gYRezyqiX6jTs7aVe42z78laJfCLMZw9e3d8H/VlMou6hllJ5hCpo5wrZX0DgmmnlQxJoQRxqwnxalg5cETdQKEzph8i1kYKtQUyqqHUdgseqa+QmREvLU8KeOIuZ3gzvvwa3GTbGDwjqJ6SUQ0rfmKoIKKIZT4yc3iaDkJkJtCyJgXKnbDJJcfN3ciSGWGZCyxIVfVbf41G83M/GBOfISmcyQRE33vH0ZBFHWVyI94mbXF951ivbrfw8J+oaVaDpJg5SqEpg0/offg99Nf/VdNF39MgiHRTYJSG/XDkfZw/iNm2B6ERYuGe1pfGIVYbiJWd3CLSEqt74XQhasX57TlT74nD+vMWGFzlSkSx/K5uj3tIjFoYiThDvFlNJa4ILVn72R8Rq4FZbMb8xgq9ECX2uJcsm9Nt9aNv3GbjOloP5uRefz1xH54ERhiOcg4c3tXWkhj3gVPn0kxuFzQH3eAGC3ObstDj3rmTOIqrww75IAeOWlyXYNTdQ06oKcG/jeVPPQhcavkfNl3/NJPB3ESXIdBBBeEiYs2Bt8loXpLfRP64aURUQMeuI9qxg7Eixg9Vre+kCE0hdaFrFAguLxo12frW9HD3NHDIkqfurYS59aMFytGfQd2JrFDLXVJNN8i55LtiwQ/2ClgPFS6YyAaXVKV5oNgJPc7nki5Xd3iJmtCk
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring
