  version: '3'
  services:
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt
      volumes:
        - ${data_path}/zigbee/z2m:/app/data
        - ${zigbee_dev_path}:/dev/ttyACM0
      ports:
        - 8090:80
        # CC251
        #- /dev/ttyUSB_cc2531:/dev/ttyACM0
        # CC2530 / GBAN GB2530S
        #- /dev/ttyUSB_cc2530:/dev/ttyACM0
      restart: always
      networks:
        - mqtt
        - caddy
      deploy:
        labels:
          # ingress
          caddy: iot.${base_domain}
          caddy.reverse_proxy: "{{ upstreams 80 }}"
          caddy.tls: internal
          # homepage
          homepage.group: ${svc_group}
          homepage.name: Zigbee2MQTT
          homepage.icon: zigbee2mqtt
          homepage.href: https://iot.${base_domain}
          homepage.description: Manager for non-WiFi smart devices
        placement:
          constraints:
            - node.labels.combee==true

    mosquitto:
      image: eclipse-mosquitto
      container_name: mosquitto
      restart: unless-stopped
      volumes:
        - ${data_path}/zigbee/mqtt/config:/mosquitto/config
        - ${data_path}/zigbee/mqtt/data:/mosquitto/data
        - ${data_path}/zigbee/mqtt/log:/mosquitto/log
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=${tz}
      networks:
        - mqtt

  networks:
    mqtt:
      external: true
    caddy:
      external: true