apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-issuer
  namespace: cert-manager
spec:
  acme:
    email: coffeeknife@proton.me
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: coffeeknife@proton.me
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token