apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAcgL/a7Ct4MIKO+yjkh8YGi+OIeTSLXiEqV5lskGy0Hvf6viXntUHgAZjaapipddPO582qVeYOqwZmMlVhxpLMjQ/u2xu9HjJ/dP7ycVsPIzvXGFJ9PeIba6/42lw+l5FeQeimz5yDiwBrr2rEk+hgRy1eG8Rn9yA1lH9v1BawOuK5GGMXDWajJPBjDmR7LIXP/hS48qDujn3xfh0lo821PfFg6/unfB1S48Dx1voRYAnt9Q7PXQaeAQ/jNX7HnH8WOwy2dHZMSfB8s70tA6ZN/3YJEhHxPX1IGJ73D0RV3MMKAHPRlRXwdmV1girUg9j6JuhpdNbbP9TkUogBLFtLBteY7dsAW2l1DAcU2QnhMF/f2bRH8IomLBJ1EUfurJ10l0CROYFtDrOjfZjRFeiuwVIWRT4etb64KQ1nvm4bEJrm9ukq62cc0SmO6tynZ9P0Ecai/HgBJ4Uc8G21MGlNA2ipCkPzeLSC0Ib8+n9fXRsj3Yjq+QS0pVdewezUP6fv3q2dgDnq+GBw+gxvIXPNXBWGWxy1v+ZEtE3Cv63gNNJ33UCp7ZwIHQhjyXWDnQF0cBGrNJ3ttNjb2IeMhtfrL8f7gVL+VIQtdgcsiW1yYf/Pk3mGfIeruEimXy5oSz824y/0blISezKKfWbnCwR2WV39SZocTcG8gBhQhnMAQ0zgZI0umWUauUWlYjU5Y1nCmNQvRWJ5Kl3AYxmPAa9Bi2grDW0lcQX8Jz9xdKSJ1FJ92/OLPCoS