apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBVAa2E5cRYLAMhjjeW7e1+x9TbprqhU4gMHbHmsYLDFd2SvcDQsGsyv7OZUrkUMQytFi83gWuWRQR0cW2c3RJfBoHhyLVPBrUQDYmHieLxyuu8qCdygR6PG8cBkxbwGSxMau+/p5EJSaNqR/JrwvufwdcXg/B70aicKCPu6IgiUYbnxx5yml/BbUif4Hj2wSeIVDaQcYRc/fhZNAKeFDTZqA/Y14pJa8DpwS4BQb0NVqW7VSSJ/jaDXJQ/2Z9P0DaNPnOQWmWdk28QRXki1xEhTf4c9IGqgG1GGKZr59toyd254KJ80vEQog2h077didfnYHNhAJTT+ojNz/nL2+RrqmYPGAa5r4ruc37LslhPnY0ZqWNpCWuAQ6u+VpSbyDE6rSij3nT6rnFZH/f9NHa8TtQS2UcSRbSc2ueWMkL3M/eaBTokwfuLX0xMNmPY73PITe7tflo4AlwJPs2VLgut8h+jt3588ZqDssbyMZJUoc4eWNfx+et0dx/Zwre5EAkZPO+xV/1+ixo9SCs1d5aNIDkC8wVwJIZ494KT7drZJUEw7xxEOfNyz/lGG/ysH+c7sF1LDM28XPnLHNtsLhmBR54g3IUg20Lmu4tf2nPGjnoFKdRDSeZqojGqKtfmSl7QjB+iwu/OnCCIxdEnlEUjKm/3oU6MAFhlsQOP0gdRsLUEc+QlT7YtUtdl4+4GTvVbZhb5SUSh6IBcPExCoQrRUMeFDm5rmAI667OkkMvcCoPhf0RQje12ow==