apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCb2y00c780lc7MKcj/eR0AE95IrMt0CeU3c9/zmIsmhUILHfuP4CyNK0OFJJUpqv1B70/3eix2A5c1KMWLlSjYjWpFPnjFgfjAxY1zyJe7I+rKHkz+c8wwaF/1e0937U7O4plYrEBJdT86/jWIQ0iFHX44xWi9Iv56qVUJ2LAuU33SQjMzHenpOYsA72paNY/Ox1CwmI10AxZKYEDrPphzA1qZPCjtA2SELRci9t0rSKXoQdxM/roSvo0utEGz6263vjFbleAXTj2iSmTY8QsBCwq2kpZcBsQ9mQ8wvszmWri0bFXf3jLU3pF6+n/13hM64HmBCJaDA455hxC7JBB1XEbAZ7szcQI33OPc7aC1pEWwm3T9z3aIQ7debUf12Q8oI5OEvGkR3cS2UUkPBMWgp39a7lkcZ/eapTwbkXGF9IDUZVbT+W/bljwkX3n2KO2smYQa9atTkD5plDjfRS31bKKYiQ+WVCsKHINP9G2mQHHhY78m8FsFwbNBp+3lodHgCqh4qqIpiM0y2SWWbd9W5IqQN154iQDUMPG1UFIEFcyLZuCnXA9/juaR+DsPoHmnjQWWeVXKUC6sA8Y/jLuVH6KH90CCoSfUBC9vQXeAD/rbUk8Mz0NPnXNKi5cWfMGlQKh5OHR7Zew+GwkR8mKqJImrYgEknhY8juzG0NBoY0mbrVvGY0ZmH+r1ZXlDngNKyiYzrP82sP3uj4wK+7XHFAiMOdNDcH8pSoqt4ucjaxx3NSkuxjy1uQ==