version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    networks:
      - caddy
      - host
    ports:
      - 8096:8096
    volumes:
      - ${jellyfin_config}:/config
      - ${jellyfin_cache}:/cache
      - ${jellyfin_media}:/media
      - ${jellyfin_gpu}:/dev/dri/renderD128 # graphics card mount location on designated node
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscover
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          memory: 8G
          cpus: '4'
      labels:
        # ingress
        caddy: ${jellyfin_domain}
        caddy.reverse_proxy: "{{ upstreams 8096 }}"
        caddy.tls: internal
        # homepage
        homepage.group: Media
        homepage.name: Jellyfin
        homepage.icon: jellyfin
        homepage.href: https://${jellyfin_domain}
        homepage.description: Home TV & movie streaming
        homepage.widget.type: jellyfin
        homepage.widget.url: http://jellyfin:8096
        homepage.widget.key: ${jellyfin_apikey}
        homepage.widget.enableNowPlaying: 'false'
        homepage.widget.enableBlocks: 'true'
        homepage.widget.fields: ${jellyfin_widgetfields}
      placement:
        constraints:
          - node.role==manager

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    networks:
      - caddy
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    depends_on:
      - jellyfin
    volumes:
      - ${jellyseerr_config}:/app/config
    deploy:
      labels:
        # ingress
        caddy: ${jellyseerr_domain}
        caddy.reverse_proxy: "{{ upstreams 5055 }}"
        caddy.tls: internal
        # homepage 
        homepage.group: Media
        homepage.name: Jellyseerr
        homepage.icon: jellyseerr
        homepage.href: https://${jellyseerr_domain}
        homepage.description: Request manager for Jellyfin
        homepage.widget.type: jellyseerr
        homepage.widget.url: http://jellyseerr:5055
        homepage.widget.key: ${jellyseerr_apikey}

        
networks:
  host:
    external: true
  caddy:
    external: true