apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: mariadb-daily
  namespace: mariadb-sys
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: database
    app.kubernetes.io/component: backup
spec:
  mariaDbRef:
    name: mariadb
  # Daily at 04:17 UTC (off the :00/:30 stampede)
  schedule:
    cron: "17 4 * * *"
    suspend: false
  maxRetention: 336h          # 14 days
  compression: gzip
  storage:
    persistentVolumeClaim:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 20Gi
      storageClassName: vulcan-nfs
