version: "3.9"

services:
  myfeedcord:
    # image: qolors/feedcord # for amd64 architecture
    image: qolors/feedcord:latest-arm64  # For arm64 architecture (Uncomment this line and comment the above if using arm64)
    volumes:
      - ${feedcord_config}:/app/config/appsettings.json
    environment:
      - TZ=America/Chicago