apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./apps/auth/authelia/manifests
  prune: true
  wait: true
  dependsOn:
    - name: mariadb
    - name: lldap