# Longhorn values - only customizations from defaults

# Storage class defaults
persistence:
  defaultDataLocality: 'best-effort'

# Prometheus integration
longhornManager:
  serviceAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: manager

metrics:
  serviceMonitor:
    enabled: true
