---
- name: Create TrueNAS VM
  hosts: proxmox

  tasks:
    - name: Create TrueNAS VM
      community.general.proxmox_kvm:
        vmid: 101
        name: truenas
        node: etheirys
        api_user: root@pam
        api_password: "{{ lookup('ansible.builtin.env', 'API_PASSWORD') }}"
        api_host: "192.168.1.53"
        cores: 2
        memory: 8192
        localtime: true
        sata:
          sata0: 'local_lvm:16'
        ide:
          ide0: 'local:iso/TrueNAS-13.0-U6.2.iso'
        state: present
        onboot: true
        ostype: l26
        hotplug: disk,network,usb,memory,cpu
        proxmox_default_behavior: compatibility
