---
- name: Install necessary packages for proxmox
  hosts: proxmox
  tasks:
    - name: Ensure proxmox packages are installed
      ansible.builtin.package:
        name:
          - python3-proxmoxer
          - python3-requests
        state: present