---
- name: Install necessary pip packages for proxmox
  hosts: proxmox
  tasks:
    - name: Ensure pipx is installed
      ansible.builtin.package:
        name: pipx
        state: present

    - name: Run pip
      community.general.pipx:
        name:
          - proxmoxer
          - requests