# TODO: make ansible playbook for one-click deployment of the whole swarm
---
- name: Initialize docker swarm
  hosts: "{{ swarm_hosts | default('workers') }}"
  tasks:
    - name: Join docker swarm
      ansible.builtin.command: "docker swarm join --token {{ join_token }} {{ controller_ip }}:2377"
      register: swarm_output
      changed_when: swarm_output.rc == 0
