apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-sonarr-nfs
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/part-of: media
spec:
  storageClassName: vulcan-nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 800Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-radarr-nfs
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/part-of: media
spec:
  storageClassName: vulcan-nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 800Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-lidarr-nfs
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/part-of: media
spec:
  storageClassName: vulcan-nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 800Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-prowlarr-nfs
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/part-of: media
spec:
  storageClassName: vulcan-nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 800Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-bazarr-nfs
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/part-of: media
spec:
  storageClassName: vulcan-nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 800Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-qbittorrent-config-nfs
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: media
spec:
  storageClassName: vulcan-nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-qbittorrent-gluetun-nfs
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: media
spec:
  storageClassName: vulcan-nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
