version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - caddy
    environment:
      - PMA_HOST=${mysql_host}
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI="https://db.${base_domain}"
    deploy:
      labels:
        # reverse proxy
        caddy: db.${base_domain}
        caddy.reverse_proxy: "{{ upstreams 80 }}"
        caddy.tls: internal
        # homepage
        homepage.group: ${infra_group}
        homepage.name: phpMyAdmin
        homepage.icon: phpmyadmin
        homepage.href: https://db.${base_domain}

networks:
  caddy:
    external: true
