version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=${mysql_host}
      - PMA_PORT=${mysql_port}
      - PMA_ABSOLUTE_URI=https://${pma_domain}
    deploy:
      labels:
        # reverse proxy
        caddy: ${pma_domain}
        caddy.reverse_proxy: "{{ upstreams 80 }}"
        caddy.tls: internal
        # homepage
        homepage.group: ${pma_group}
        homepage.name: phpMyAdmin
        homepage.icon: phpmyadmin
        homepage.href: https://${pma_domain}
