---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digest-auth-token
  namespace: homelab-digest
spec:
  encryptedData:
    token: AgB89ooG2OPraYkOpdU90D3ACVrC6lL6YgesFMVweuh3CmbeP/3LQzyaqhz2Ne3jkTL8fn19ar5iCEEJQG9mBCESihVKJCUiVtUgVee8E1uUx5Pe46daR6JcQIEP8lJWgEJQivKbvbApqVANq/hs+D3Ag1n3QqS7o0Lhpo2MzE9p4JkZPSSc9O01VADauBsSCG9RY0EA1lF4SKMgIpT72AZi1OO8wYUuuybmr82WoYxVRJLm5Iq/3d29XZipqOnwJpHQNIy+065EWqGN35ar54VjCjadOqbV02zgetzOQ6fR7gs2spZauE8RskbvK1aS0JTtym8ckHjRqw62eus//NLGdSZTdC2Am8y06ZQR7su5QO+K8K7pWF3mCSh3vaVl+JqzO7Imj/dn/zecqsZj0HKICuhvi6fGKqXqtXZjhYI2IxR88uPdyGibJxopuzlOx+1dUmggK56FIJ1B+xl2ZWIy/AdhDFVkftqDGVEyzESsZy4IX83KCViJE2+lqTA7QjU35FQd0O9HLGdF9Es6wvEqo3NgLvt2ppZXiFOVDz6qzeMD/x8ClT3XxoyQih17g+yyYq9QV9jblylEUgKiwRMKRVWE7RtaI+KK9kpoRJpyCvUUWzqJ8Kzw+6L9DgKTKPxBKDFzOFRtzWvsjhNpUwPDunVT/uI16ttnD19eemcOqci9lTM+ftzoJPrgqYo9xWLsWApbAmsvVwWwZudxfgdYHLb9j3N+SE+eFfM191kcDs+PIhg7PZlgC7RQbt5KTUnukEiqmoSiMO3kFpMPGNzx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homelab-digest
        app.kubernetes.io/part-of: monitoring
      name: digest-auth-token
      namespace: homelab-digest
