configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.0.0.0/8
  templateConfig: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    {{- if or .Values.ingress.enabled .Values.ingress.external }}
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        {{- range .Values.configuration.trusted_proxies }}
        - {{ . }}
        {{- end }}
    {{- end }}
    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    recorder:
      db_url: !env_var RECORDER_DB_URL
      purge_keep_days: 30
      commit_interval: 5

addons.codeserver.enabled: true

env:
  - name: RECORDER_DB_URL
    valueFrom:
      secretKeyRef:
        name: hass-recorder-creds
        key: db_url

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: vulcan-nfs-strict
  matchLabels:
    hass-config-pv: "true"

priorityClassName: high-priority

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /auth/providers
    port: 8123
  initialDelaySeconds: 180
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /auth/providers
    port: 8123
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 5

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: cert-issuer
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/group: "Core"
    gethomepage.dev/icon: "home-assistant"
    gethomepage.dev/description: "Home automation"
    gethomepage.dev/href: "https://home.wrenspace.dev/auth/oidc/welcome"
    gethomepage.dev/weight: "50"
  hosts:
    - host: home.wrenspace.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - home.wrenspace.dev
      secretName: hass-tls