apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db
  namespace: postgres-db
spec:
  instances: 2 # You requested a single server
  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi # Adjust storage size as needed

  # Defines the default superuser for administrative access
  superuserSecret:
    name: postgres-superuser-secret
  
  serviceTemplate:
    - metadata:
        name: postgres-nodeport
      spec:
        type: NodePort
        selector:
          cnpg.io/cluster: postgres-db
          cnpg.io/instanceRole: primary
        ports:
          - port: 5432
            targetPort: 5432
            nodePort: 30432 

  managed:
    roles:
      - name: robin
        passwordSecret:
          name: admin-secret