apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db
  namespace: postgres-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi 
  managed:
    roles:
      - name: robin
        passwordSecret:
          name: admin-secret
        login: true
        superuser: true
        inRoles:
          - pg_monitor