apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: postgres-db
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: postgres-db
    cnpg.io/instanceRole: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432 