apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease-nfs.yaml
  - helmrelease-iscsi.yaml
  # After sealing secrets per secrets.template.yaml, add them here:
  # - nfs-config.yaml
  # - iscsi-config.yaml
